#!/usr/bin/env bash
# Continuous Learning v3 - Installation Script
#
# Creates directory structure, merges hooks into settings.json,
# creates initial learned.md, and optionally starts observer.
#
# Usage:
#   bash install.sh          — Full install
#   bash install.sh --hooks  — Only update hooks in settings.json

set -euo pipefail

CL_DIR="$HOME/.claude/continual-learning"
SETTINGS="$HOME/.claude/settings.json"
RULES_DIR="$HOME/.claude/rules"

echo "=== Continuous Learning v3 Installer ==="
echo ""

# ─────────────────────────────────────────────
# Step 1: Create directory structure
# ─────────────────────────────────────────────

echo "1. Creating directory structure..."

dirs=(
    "$CL_DIR/hooks"
    "$CL_DIR/observer"
    "$CL_DIR/instincts/personal"
    "$CL_DIR/instincts/inherited"
    "$CL_DIR/data/turns.archive"
    "$CL_DIR/cli"
    "$CL_DIR/prompts"
    "$CL_DIR/evolved/skills"
    "$CL_DIR/evolved/commands"
    "$CL_DIR/evolved/agents"
    "$RULES_DIR"
)

for d in "${dirs[@]}"; do
    mkdir -p "$d"
done

echo "   Done."

# ─────────────────────────────────────────────
# Step 2: Verify core files exist
# ─────────────────────────────────────────────

echo "2. Checking core files..."

required_files=(
    "$CL_DIR/hooks/record.sh"
    "$CL_DIR/hooks/dispatcher.sh"
    "$CL_DIR/hooks/hooks.json"
    "$CL_DIR/hooks/intercept.py"
    "$CL_DIR/observer/daemon.sh"
    "$CL_DIR/observer/build_episodes.py"
    "$CL_DIR/observer/episode_prompt.md"
    "$CL_DIR/observer/pattern_prompt.md"
    "$CL_DIR/observer/extract_bash_contexts.py"
    "$CL_DIR/observer/bash_pattern_prompt.md"
    "$CL_DIR/cli/instinct_cli.py"
    "$CL_DIR/config.json"
)

missing=0
for f in "${required_files[@]}"; do
    if [ ! -f "$f" ]; then
        echo "   MISSING: $f"
        missing=$((missing + 1))
    fi
done

if [ "$missing" -gt 0 ]; then
    echo "   ERROR: $missing core files missing. Please ensure all files are created."
    exit 1
fi

# Ensure scripts are executable
chmod +x "$CL_DIR/hooks/record.sh"
chmod +x "$CL_DIR/hooks/dispatcher.sh"
chmod +x "$CL_DIR/observer/daemon.sh"
chmod +x "$CL_DIR/observer/build_episodes.py"
chmod +x "$CL_DIR/observer/extract_bash_contexts.py"
chmod +x "$CL_DIR/cli/instinct_cli.py"

echo "   All core files present."

# ─────────────────────────────────────────────
# Step 3: Create initial learned.md (if not exists)
# ─────────────────────────────────────────────

echo "3. Setting up rules..."

LEARNED_MD="$RULES_DIR/learned.md"
if [ ! -f "$LEARNED_MD" ]; then
    cat > "$LEARNED_MD" << 'HEREDOC'
# Learned Preferences (auto-generated by continual-learning-v3)
# Last updated: not yet analyzed
# Source: observer v3 pattern detection
# Do not edit manually - changes will be overwritten by observer
HEREDOC
    echo "   Created $LEARNED_MD"
else
    echo "   $LEARNED_MD already exists, skipping."
fi

BASH_INSIGHTS="$RULES_DIR/bash_insights.md"
if [ ! -f "$BASH_INSIGHTS" ]; then
    cat > "$BASH_INSIGHTS" << 'HEREDOC'
# Bash Tool Insights (auto-generated by continual-learning-v3)
# Last updated: not yet analyzed
# Source: observer v3 bash pattern detection
# Do not edit manually - regenerate with: cl bash-insight sync

There are 0 active bash command insights. These represent learned preferences
for how certain bash commands should be executed.

## Active Insights Summary

No bash insights detected yet. Insights will be added automatically by the
observer when recurring bash command corrections are detected, or manually
via `cl bash-insight add`.

## How to Use

- Before running bash commands in flagged domains, consider the alternative
- If a bash command is blocked by an insight, the block message will explain why
- To intentionally bypass: prepend `CL_SKIP=<insight_id>` to the command
- To disable all interception for one command: prepend `CL_BASH_INTERCEPT=0`
- To view full details: use `cl bash-insight list`
HEREDOC
    echo "   Created $BASH_INSIGHTS"
else
    echo "   $BASH_INSIGHTS already exists, skipping."
fi

# ─────────────────────────────────────────────
# Step 4: Merge hooks into settings.json
# ─────────────────────────────────────────────

echo "4. Configuring hooks in settings.json..."

if [ ! -f "$SETTINGS" ]; then
    echo '{}' > "$SETTINGS"
fi

# Use Python for safe JSON merging (preserves existing hooks)
python3 << 'PYEOF'
import json
import sys
from pathlib import Path

settings_path = Path.home() / ".claude" / "settings.json"
cl_dir = "~/.claude/continual-learning"

# New v3 hooks to add (unified dispatcher replaces direct record.sh calls)
v3_hooks = {
    "UserPromptSubmit": [{
        "hooks": [{
            "type": "command",
            "command": f"{cl_dir}/hooks/dispatcher.sh user_prompt"
        }]
    }],
    "PreToolUse": [{
        "matcher": "*",
        "hooks": [{
            "type": "command",
            "command": f"{cl_dir}/hooks/dispatcher.sh pre_tool"
        }]
    }],
    "PostToolUse": [{
        "matcher": "Bash",
        "hooks": [{
            "type": "command",
            "command": f"{cl_dir}/hooks/dispatcher.sh post_tool"
        }]
    }],
    "PostToolUseFailure": [{
        "matcher": "*",
        "hooks": [{
            "type": "command",
            "command": f"{cl_dir}/hooks/dispatcher.sh tool_fail"
        }]
    }],
    "Stop": [{
        "hooks": [{
            "type": "command",
            "command": f"{cl_dir}/hooks/dispatcher.sh stop"
        }]
    }]
}

# Also identify old record.sh hooks to replace
old_record_patterns = ["record.sh"]

# Load existing settings
try:
    settings = json.loads(settings_path.read_text())
except Exception:
    settings = {}

existing_hooks = settings.get("hooks", {})

# Remove old hooks (observe.sh and direct record.sh references)
for hook_type in list(existing_hooks.keys()):
    entries = existing_hooks[hook_type]
    if isinstance(entries, list):
        filtered = []
        for entry in entries:
            hooks_list = entry.get("hooks", [])
            # Filter out v2 observe.sh hooks and old direct record.sh hooks
            clean_hooks = [h for h in hooks_list
                          if "observe.sh" not in h.get("command", "")
                          and "record.sh" not in h.get("command", "")]
            if clean_hooks:
                entry["hooks"] = clean_hooks
                filtered.append(entry)
        existing_hooks[hook_type] = filtered

# Merge v3 hooks (append, don't replace existing non-v2 hooks)
for hook_type, v3_entries in v3_hooks.items():
    if hook_type not in existing_hooks:
        existing_hooks[hook_type] = []

    # Check if v3 hook already registered
    existing_cmds = set()
    for entry in existing_hooks[hook_type]:
        for h in entry.get("hooks", []):
            existing_cmds.add(h.get("command", ""))

    for v3_entry in v3_entries:
        v3_cmd = v3_entry.get("hooks", [{}])[0].get("command", "")
        if v3_cmd not in existing_cmds:
            existing_hooks[hook_type].append(v3_entry)

settings["hooks"] = existing_hooks
settings_path.write_text(json.dumps(settings, indent=2) + "\n")
print("   Hooks configured successfully.")
PYEOF

# ─────────────────────────────────────────────
# Step 5: Check for v2 data migration
# ─────────────────────────────────────────────

echo "5. Checking for v2 data..."

V2_DIR="$HOME/.claude/homunculus"
if [ -d "$V2_DIR/instincts/personal" ] && [ "$(ls -A "$V2_DIR/instincts/personal" 2>/dev/null)" ]; then
    v2_count=$(find "$V2_DIR/instincts/personal" -name "*.yaml" 2>/dev/null | wc -l)
    echo "   Found $v2_count v2 instincts in $V2_DIR"
    echo ""
    read -p "   Migrate v2 instincts to v3? [y/N] " -r migrate
    if [[ "$migrate" =~ ^[Yy]$ ]]; then
        for f in "$V2_DIR/instincts/personal"/*.yaml; do
            [ -f "$f" ] && cp "$f" "$CL_DIR/instincts/personal/"
        done
        echo "   Migrated to $CL_DIR/instincts/personal/"
    fi
else
    echo "   No v2 data found."
fi

# ─────────────────────────────────────────────
# Step 6: Summary
# ─────────────────────────────────────────────

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Directory: $CL_DIR"
echo "Config:    $CL_DIR/config.json"
echo "Rules:     $RULES_DIR/learned.md"
echo ""
echo "Usage:"
echo "  python3 $CL_DIR/cli/instinct_cli.py status       Show instincts"
echo "  python3 $CL_DIR/cli/instinct_cli.py observer start  Start observer"
echo "  python3 $CL_DIR/cli/instinct_cli.py materialize     Generate rules"
echo ""

# Optionally start observer
read -p "Start observer daemon now? [y/N] " -r start_obs
if [[ "$start_obs" =~ ^[Yy]$ ]]; then
    "$CL_DIR/observer/daemon.sh" start
fi
